### ISSUE TITLE
Lattice Vectors

### ISSUE THREAD

**Issue by anthmanni** [edmundsj/RCWA#6]
Thank you so much for writing this python extension! Haven't been able to get other RCWA extensions to install on my mac, so this simple pip install was an answer to my prayers.

Could you please post an example script for calculating RT coefficients for a single-layer grating or 2D photonic crystal?
I'm trying to set my lattice vectors but haven't found a syntax that the function will trust to run the simulation. A simple reply with an example of how to define crystal layers would be great.

Thanks!

**Comment by edmundsj** [comment]
Thanks :D Nice to see it might actually be useful. I'll take a look over the weekend and see what I can do.
